### ISSUE TITLE
Roll-call API

### ISSUE THREAD

**Issue by ansarizafar** [mikeal/peer-call#111]
I want to use my own ui component to make calls. Could you please provide API methods to make a call without sending the room url. Is it possible to use IP address for both peers to make a call?

**Comment by mikeal** [comment]
WebRTC doesn't allow you to call a specific IP address for connection information.

Roll Call uses a swarm library called `killa-beez` which uses `signal-exchange` to setup signaling with initial peers using throw-away public/private keypairs. It also uses `room-exchange` for finding peers in a specific room.

If you want to make your own UI then you should just use those libraries rather than an API roll call provides.
