### ISSUE TITLE
Ability to record multiple times in succession

### ISSUE THREAD

**Issue by kimberleyhansen** [mikeal/peer-call#24]
I should be able to record for a bit, download the files, and then record again without reloading the page.

**Comment by mikeal** [comment]
Agreed.

There's a few things to consider here.
1. Right now, if you reload the page or move away from the page, you can't ever download those audio files again. We're writing them to File() objects so we _could_ recover them, we just don't store the information anywhere.
2. Recording _should_ set some kind of id for each recording. Best way to do this would probably be to append it to the querystring. That, along with some other local storage code, would allow people to recover the audio files if they go back to that URL.
3. Once each recording has a unique URL and is recoverable it should be no problem for users to do several recordings in a row without reloading.

**Comment by mikeal** [comment]
The new web experience is quite different. Simplified and very "disposable."

In the new experience it makes sense to just have people refresh the page when they wanna record again.

The desktop experience will be a bit different and include features like this, but I want to keep the web experience somewhat disposable so that it's easy to invite people and get them on.
