### ISSUE TITLE
Transcode webm to mp3 or ogg

### ISSUE THREAD

**Issue by kimberleyhansen** [mikeal/peer-call#25]
No one knows how to handle webm ;)

**Comment by mikeal** [comment]
I agree that it is quite annoying :)

Currently, webm is the only container that works OOTB in MediaRecorder on Chrome. There are some pure JS implementations of mp3 and ogg but until [this bug is fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=482934) we won't be able to quickly do a mixdown or convert to wav without playing the entire audio file :(

**Comment by mikeal** [comment]
Related https://github.com/zhuker/lamejs

**Comment by mikeal** [comment]
Closing for now.

My current thoughts on this: the Desktop client should have an audio editor. Doing this on the web is terrible, we need full ffmpeg bindings, which means it'll have to be desktop only.
