### ISSUE TITLE
Distrortion / Bad sound

### ISSUE THREAD

**Issue by ArthurDeRoey** [mikeal/peer-call#51]
While testing rollcall I get distortions and bad sound. I like the simplicity, but the sound reliability needs to change for me to adopt it. Anybody know why this issue emerged and how to fix it?

**Comment by mikeal** [comment]
I'm curious what the distortion sounds like. Is it too much background noise? Does it sound overly compressed?

**Comment by Nateowami** [comment]
I don't know if this is what is being talked about, but there's a lot of echo. Even with devices at opposite ends of the house, it echos a couple times. With the volume a little higher it starts high-pitched screeching. It really makes it almost unusable. Has this not been an issue for you?

On a side note, is the call audio encrypted end-to-end? I don't see this stated in the README, which leads me to believe it's being sent in "plain text."

**Comment by mikeal** [comment]
> I don't know if this is what is being talked about, but there's a lot of echo. Even with devices at opposite ends of the house, it echos a couple times. With the volume a little higher it starts high-pitched screeching. It really makes it almost unusable. Has this not been an issue for you?

It's an issue if you don't have headphones on. Sometimes I can even hear echo from someone's headphones if the gain is up enough, that's why we need to bring the default way down.

> On a side note, is the call audio encrypted end-to-end? I don't see this stated in the README, which leads me to believe it's being sent in "plain text."

WebRTC is entirely encrypted end-to-end.

We also use a system for doing the signal-exchange that is additionally encrypted so that the service can't read the signals :)

**Comment by Nateowami** [comment]
@mikeal Ah, thanks. I show what an ignoramus I am when it comes to WebRTC. One of the things listed under the "should be" requirements is "Third parties (like Governments) should not be able to track users or listen to calls." Then below it says "Admittedly, Roll Call doesn’t accomplish all of this today, but what it does do today..." Perhaps it should then list fairly good security as a feature (otherwise it looks like one of the things it should ideally do but doesn't).

Back on topic, are there plans to filter out the audio echo? Not sure how complicated that is or whether there are existing audio filtering implementations that could be used. But it would make Roll Call hugely more useful.

**Comment by mikeal** [comment]
@Nateowami the security is already pretty good but what we don't do is relay data through "super node" peers in order to get people around hostile networks :)
