### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by FotoVerite** [mikeal/peer-call#55]
We should consider adding in basic ui and unit tests. Probably faster then loading the site each time to bundle and see changes.

**Comment by mikeal** [comment]
Ya, this stuff is incredibly hard to test. I'm +1 on any automation we can do as long as it doesn't take crazy backflips to make it work.

I have contacts at Sauce Labs we can tap if necessary.

**Comment by FotoVerite** [comment]
Anyone want to get on a call for this tonight to talk about this, the slow bundling and how we want to break up index.js.

**Comment by mikeal** [comment]
We will probably end up doing a call about index.js refactoring as an outgrowth of https://github.com/mikeal/roll-call/issues/41 but we should do another separate one for tests as well.

**Comment by zcei** [comment]
For the slow bundling it might make sense to switch to webpack while the product still is in its early days.
Incremental builds / hot reloading would speed up bundling time, and "auto refreshs" the page without actually reloading the browser tab. (Though that would need a frontend architecture that allows hot reloading. Most known one would be `react`)

When building a _product_ instead of a prototype, one should consider changing underlaying templating tools. I think they work for now, but won't be useable for bigger things. Plus: [who's using jQuery either way?](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#.81rbz7ctx) 😉 

I think this would benefit testing as well.

EDIT: just saw there is #41 - then we might have to develop some hot reloading implementation for polymer (which seems to be [rather hard](http://stackoverflow.com/a/36693793))
But bundling everything from the very beginning on each small change seems a bit overkill.

**Comment by mikeal** [comment]
Someone on twitter mentioned webpack2 as well. I'm not familiar enough with these to judge them either way, all I really care about is:
- Good and fast dev experience.
- Minimal to zero "framework"
- Bundled file should still be ES6, rather than ES5.

**Comment by FotoVerite** [comment]
https://github.com/mikeal/roll-call/pull/75/files

**Comment by FotoVerite** [comment]
So many issue with testing right now. From weird failures to timeouts if you have another version open. We have a lot of work to do to get this working for all developers.

**Comment by mikeal** [comment]
Totally new version.

We probably need to use webdriver at this point. We're entirely dependent on WebComponents.
