### ISSUE TITLE
Request: Chrome Extension

### ISSUE THREAD

**Issue by htirma** [mikeal/peer-call#56]
An extension for Chrome would be great!

**Comment by mikeal** [comment]
What would the Chrome extension do?

Would it overlay on the current site?

I'm curious because I'd definitely like a Desktop app using Electron at some point as well. If we get good requirements for the Chrome extension as well as the desktop app we can break up the code in a refactor to help it along.

**Comment by htirma** [comment]
I was thinking making calls out of the extension without having the need to keep a tab open throughout the call. That's all I could think of for now..

**Comment by mikeal** [comment]
At this point I'm thinking it's more likely that we'll have a Desktop app than a Chrome extension.
