### ISSUE TITLE
Custom room names and administration.

### ISSUE THREAD

**Issue by htirma** [mikeal/peer-call#70]
It'd be great if I could create my own room with a custom slug like rollcall.audio/myteam and protect it with a password.
If databases are going to be a problem, something can be done with tools like http://horizon.io/ i'm hoping.
Personally, one of the best things I like about roll call is the ability to run out of GitHub Pages and would love for it to remain that way.

**Comment by FotoVerite** [comment]
@mikeal will hyperlog be safe to store passwords? It be great just to use http_basic auth for this.

**Comment by mikeal** [comment]
@FotoVerite we can't store the password in hyperlog because you have to be connected to the swarm in order to get the hyperlog data. 

I'd like to understand the use case a bit more. I don't entirely get why this is useful because a password is just a shared secret. If you generate a random room name that can essentially function as the shared secret. We go to great lengths not to leak it, you can't list the rooms in `room-exchange`, there's no tracking or any way to tell which rooms are "live," etc.

**Comment by htirma** [comment]
Random slugs are ~hard~ pretty impossible to remember, on the other hand if I had a custom slug that I could easily share with a common password or any other mode of authentication, it'd make the experience more personal and relieve a major pain point IMO.

**Comment by Edward-Stryfe** [comment]
Ok I saw this one and thought this might be helpful. 

I just copied the project and ran it on my server to test it out and it worked perfectly. The only thing is that when I got the room keys while they were different from both roll-call.audio and localhost if I used the same key on both they'd connect like a normal room. I also went ahead and just put a five character value in instead of the long slug. And it connected like a normal room and when I put the same value in both of them they connected without a hitch. 

So really they'd be painfully easy to make but it'd be messy if they were purposefully used as a part of the project cause say if businesses or someone discussing sensitive information exposed to anyone who had the same idea for a custom slug. Though in reality anyone discussing sensitive information would probably use the slug instead. If we did promote the use of the custom slugs people could start forming communities using custom slugs possibly. That is if we didn't regulate the custom slugs any.

**Comment by mikeal** [comment]
@Edward-Stryfe Exchanging signals and getting the list of seed peers uses public infrastructure so regardless of where you host the static files you're going to end up connecting to the same peer networks.

If you want to run a private version all you need to do is run a [`room-exchange`](https://github.com/mikeal/room-exchange) and a [`signal-exchange`](https://github.com/mikeal/signal-exchange) and alter those variables in the code. When we re-factor the code we should make this more easily configurable.

**Comment by Edward-Stryfe** [comment]
Alright I haven't followed this project I just tried out for myself and came across this issue and since it mentioned custom urls I thought I'd mention that it's already possible and since it was public like that I wasn't sure if that was intended, or if the service was meant to be more secure and private. 

But how about the fact that you can make a custom url as is do you plan on adding a form to make it a mainstream feature or is it going to be left as is?

**Comment by mikeal** [comment]
@Edward-Stryfe yup, it's sort of a "hidden feature" now but it's on the list of changes we want to see on the main page.

**Comment by Edward-Stryfe** [comment]
Alright I really love this product by the way. I use it frequently now that I've discovered it, it causes a lot less stress on my computer than applications like Skype or Discord. Keep up the fantastic work, really appreciate it.

**Comment by mikeal** [comment]
@Edward-Stryfe thanks! great to hear it work so well for you :)

**Comment by mikeal** [comment]
Keeping this as a "hidden" feature so that the UI and default experience can remain simple.

Documented this feature in faq.html though.
