### ISSUE TITLE
Unable to stop recording

### ISSUE THREAD

**Issue by bfbraum** [mikeal/peer-call#94]
This may or may not be relevant, but we started out with four people visible on the call; call them Alex, Bill, Carl, Dave. Before long, a fifth caller became visible: to Bill, it looked like a clone of Dave, but to Dave, it looked like a clone of Bill. Alex and Carl didn't chime in, so I'm not sure what they saw. The seemingly-cloned process stopped recording at that point. This happened twice more, when Alex and Carl saw the cat in the upper-right corner, clicked on it, and involuntarily left the page. (This was our first time using roll call, as you might have guessed.)

At some point, though, Bill, who had initiated the call, noticed that the stop-recording button had been greyed out. When the others closed their browser windows, he was able to download their individual voice recordings. (This is an awesome feature, by the way.) But he wasn't able to stop the recording and download his own.

**Comment by mikeal** [comment]
Strange that the person who started recording couldn't complete it, not sure what that bug was.

The repeated callers is probably from re-connects. I've seen this before when someone's local network connection was kill their connection every 60 seconds. What we do in that case is preserve the UI for the disconnected call so that you can download their audio still but we should probably make that clearer.

We also encode the delay of each track into the filename but once Chrome fixes their decodeAudioData bug we'll be able to mix them down and re-align all on our own.

**Comment by mikeal** [comment]
Should be fixed in new version.
